local p = {
    ["13730"] = {
        barrages = {
            {
                name = "Encore Flare",
                parts = {
                    {
                        damage        = 30,
                        coefficient   = 1,
                        count         = 6,
                        stat          = "fp",
                        ratio         = 1,
                        armor_mod     = { 1.2, 1.2, 1.2 },
                        ammo          = 2,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 35 },
                        aim_type      = 0,
                        angle         = 360,
                        splash        = 0,
                        velocity      = 12,
                        pierce        = 99,
                        shell_range   = { 25, 35 },
                        spread        = { 0, 0 },
                        buffs         = {
                            "Increase DMG taken by 10% for 6s",
                            "If only one enemy was hit set speed to 0 for 3s"
                        },
                        buff_chance   = 1,
                    },
                    {
                        damage        = 62,
                        coefficient   = 1,
                        count         = 1,
                        stat          = "asw",
                        ratio         = 1,
                        armor_mod     = { 1.2, 1.2, 1.2 },
                        ammo          = 1,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 30 },
                        aim_type      = 1,
                        angle         = 360,
                        splash        = 12,
                        velocity      = 10,
                        pierce        = 0,
                        shell_range   = { 15, 25 },
                        spread        = { 0, 0 },
                        buffs         = {
                            "Increase DMG taken by 10% for 6s",
                            "If only one enemy was hit set speed to 0 for 3s"
                        },
                        buff_chance   = 1,
                    },
                    {
                        damage        = 50,
                        coefficient   = 1,
                        count         = 6,
                        stat          = "trp",
                        ratio         = 1,
                        armor_mod     = { 0.8, 1, 1.3 },
                        ammo          = 4,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 90 },
                        aim_type      = 1,
                        angle         = 120,
                        splash        = 3,
                        velocity      = 2,
                        pierce        = 0,
                        shell_range   = { 70, 110 },
                        spread        = { 0, 0 },
                    },
                },
            },
        },
        ships = { "Roon μ" },
    },
    ["13740"] = {
        barrages = {
            {
                name = "Bilateral Accompaniment",
                parts = {
                    {
                        damage        = 50,
                        coefficient   = 1,
                        count         = 8,
                        stat          = "fp",
                        ratio         = 1,
                        armor_mod     = { 1, 1, 1 },
                        ammo          = 1,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 90 },
                        aim_type      = 1,
                        angle         = 120,
                        splash        = 3,
                        velocity      = 2,
                        pierce        = 0,
                        shell_range   = { 70, 110 },
                        spread        = { 0, 0 },
                    },
                },
            },
        },
        ships = { "Roon μ" },
    },
    ["29612"] = {
        barrages = {
            {
                name = "All Out Assault - Roon μ II",
                parts = {
                    {
                        damage        = 30,
                        coefficient   = 1.1,
                        count         = 16,
                        stat          = "fp",
                        ratio         = 1,
                        armor_mod     = { 1.35, 0.95, 0.7 },
                        ammo          = 3,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 50 },
                        aim_type      = 0,
                        angle         = 360,
                        splash        = 0,
                        velocity      = 18,
                        pierce        = 0,
                        shell_range   = { 70, 90 },
                        spread        = { 0, 0 },
                        buffs         = {
                            "Standard Burn (DMG equal to 5 + WepDMG * WepCoeff * (1 + (FP / 100)) * 0.6 with 1 tick every 3 seconds for 15.1s, ID: 311)",
                        },
                        buff_chance   = 0.08,
                    },
                    {
                        damage        = 30,
                        coefficient   = 1.1,
                        count         = 16,
                        stat          = "fp",
                        ratio         = 1,
                        armor_mod     = { 1, 1.3, 1.3 },
                        ammo          = 2,
                        is_critical   = false,
                        notes         = {},
                        shrapnel      = false,
                        ignore_shield = false,
                        range         = { 0, 50 },
                        aim_type      = 0,
                        angle         = 360,
                        splash        = 0,
                        velocity      = 18,
                        pierce        = 1,
                        shell_range   = { 70, 90 },
                        spread        = { 0, 0 },
                    },
                },
            },
        },
        ships = { "Roon μ" },
    },
}

return p
