name: gsheets2img

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 21.6.2
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.2'

    - name: Change directory and run scripts
      run: |
        cd dev_tools/gsheets2img
        rm -rf node_modules
        npm install
        npm start

    - name: Check for changes
      id: git-check
      run: |
        rm -rf node_modules
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ../../images/
        git diff-index --quiet HEAD || echo "::set-output name=changes::true"
        git commit -m "$(TZ='America/Los_Angeles' date +'%Y-%m-%d') Equip & Misc. Update" || echo "No changes to commit"
      shell: bash

    - name: Push changes
      if: steps.git-check.outputs.changes == 'true'
      run: git push origin main
